import sketch1 from "./img/sketch1.jpeg";
import sketch2 from "./img/sketch2.jpeg";
import sketch3 from "./img/sketch3.jpeg";
import sketch4 from "./img/sketch4.jpeg";
import sketch5 from "./img/sketch5.jpg";
import sketch6 from "./img/sketch6.png";

import { YellowSticky, PinkSticky, PurpleSticky, GreenSticky, BlueSticky } from "./colored-sticky-styles";
export const StickyLinkData = [
  {
    key: 0,
    color: BlueSticky,
    links: ["https://ravel.neocities.org/"],
    position: { x: 20, y: 20 },
  },
  {
    key: 1,
    color: YellowSticky,
    links: ["https://noodledesk.net/"],
    position: { x: 120, y: 350 },
  },
  {
    key: 2,
    color: GreenSticky,
    links: ["https://mushroomcoloratlas.com/"],
    position: { x: 650, y: 0 },
  },
  {
    key: 3,
    color: PurpleSticky,
    links: ["https://kenyonreview.org/kr-online-issue/2019-janfeb/selections/sarah-thankam-mathews-342846/"],
    position: { x: 450, y: 300 },
  },
  {
    key: 4,
    color: BlueSticky,
    links: ["https://adriantomine.substack.com/"],
    position: { x: 600, y: 500 },
  },
  {
    key: 5,
    color: YellowSticky,
    links: ["https://www.onasunbeam.com/"],
    position: { x: 800, y: 100 },
  },
  {
    key: 6,
    color: PinkSticky,
    links: ["http://datamoshing.com/"],
    position: { x: 780, y: 200 },
  },
  {
    key: 7,
    color: PurpleSticky,
    links: ["https://surabhisaraf.net/alaap"],
    position: { x: 180, y: 200 },
  },
  {
    key: 9,
    color: GreenSticky,
    links: ["https://gifcities.org/?q=computer", "https://multiverse.plus/cinni/mood-board"],
    position: { x: 1000, y: 300 },
  },
  {
    key: 10,
    color: PinkSticky,
    links: ["https://chiaski.github.io/poeticweb/", "https://www.are.na/dani-bloop/the-internet-as-a-place-of-empathy"],
    position: { x: 370, y: 150 },
  },
  {
    key: 11,
    color: YellowSticky,
    links: ["https://mutazionegame.com/", "https://epiloguegaming.com/escaping-to-mutazione-island/"],
    position: { x: 250, y: 380 },
  },
  {
    key: 12,
    color: BlueSticky,
    links: ["https://whenwe.love", "https://whenwe.love/moving", "https://whenwe.love/gazing", "https://whenwe.love/cloudwatching"],
    position: { x: 150, y: 510 },
  },
  {
    key: 13,
    color: PurpleSticky,
    links: ["https://matthewrayfield.com", "https://6vcr.com"],
    position: { x: 950, y: 10 },
  },
  {
    key: 14,
    color: YellowSticky,
    links: ["https://www.texasmonthly.com/arts-entertainment/houston-prophetic-city-or-pathetic-city/"],
    position: { x: 950, y: 400 },
  },
  {
    key: 19,
    color: BlueSticky,
    links: ["sign up by march 12th!!!", "https://www.href.place"],
    position: { x: 1100, y: 350 },
  },
];

export const StickyImageData = [
  {
    key: 15,
    color: GreenSticky,
    image: sketch1,
    position: { x: 250, y: 100 },
  },
  {
    key: 16,
    color: PurpleSticky,
    image: sketch2,
    position: { x: 450, y: 300 },
  },
  {
    key: 17,
    color: YellowSticky,
    image: sketch3,
    position: { x: 750, y: 350 },
  },
  {
    key: 18,
    color: PinkSticky,
    image: sketch4,
    position: { x: 1150, y: 70 },
  },
  {
    key: 20,
    color: PurpleSticky,
    image: sketch5,
    position: { x: 760, y: 250 },
  },
  {
    key: 21,
    color: GreenSticky,
    image: sketch6,
    position: { x: 510, y: 450 },
  },
];

export const ReceivedLinkData = [
  { name: "Rachel", link: ["http://www.eastgate.com/garden/Introduction.html"] },
  { name: "rudy", link: ["https://web.archive.org/web/20140310190221/http://www.sewingandembroiderywarehouse.com/embtrb.htm"] },
  { name: "musicworm", link: ["https://seaexcursion.itch.io/topograph"] },
  { name: "jessica", link: ["https://youtu.be/vv_alwQL8L4"] },
  { name: "jonas", link: ["https://second-brain.neocities.org/"] },
  { name: "Amy", link: ["http://stoney.sb.org/eno/oblique.html"] },
  { name: "Laura", link: ["https://www.themarginalian.org/"] },
  { name: "Laura", link: ["https://publicdomainreview.org/"] },
  { name: "Laura", link: ["https://www.shauntan.net/"] },
  { name: "helen", link: ["https://colorfiction.itch.io/nightline"] },
  { name: "helen", link: ["https://touchterrain.geol.iastate.edu"] },
  { name: "helen", link: ["hedonometer.org"] },
  { name: "Andy!", link: ["https://web.archive.org/web/20140310190221/http://www.sewingandembroiderywarehouse.com/embtrb.htm"] },
  {
    name: "Moop!",
    link: ["https://static.boredpanda.com/blog/wp-content/uploads/2017/06/adorable-cute-raccoons-68-595642de22445__700.jpg"],
  },
  { name: "ear", link: ["https://www.artbasel.com/catalog/artwork/85679/Friedrich-Kunath-Sorry-But-I-Have-A-Dream-To-Catch"] },
  { name: "zumdar", link: ["https://tilde.town/"] },
  { name: "ish", link: ["https://www.asoundthatneverwas.net"] },
  { name: "lizz thabet", link: ["https://thebaffler.com/salvos/whats-the-point-if-we-cant-have-fun"] },
  { name: "zhen", link: ["https://fungal.page"] },
  { name: "max", link: ["https://www.insulators.info/"] },
  { name: "Laxu", link: ["https://youtu.be/3weBlcyJHlQ"] },
  { name: "haraldpeter", link: ["https://www.digitalgarden.nu/"] },
  { name: "Kristoffer", link: ["http://Wilderness.land"] },
  { name: "Taylor", link: ["https://www.digitalgarden.nu/"] },
  { name: "chia", link: ["https://tinybird.zone/"] },
  { name: "Dinah", link: ["https://birdcast.info/"] },
  { name: "roma", link: ["https://journals.aau.dk/index.php/JOS"] },
  { name: "Sam", link: ["http://www.jesusisprecious.org"] },
  { name: "Sarah Eadie", link: ["https://web.archive.org/web/20000819124122/http://www.smbhq.com/dance/"] },
  { name: "rain/rin", link: ["https://rainydaysphotos.myportfolio.com/"] },
  { name: "Ali", link: ["https://alt.pavethe.earth/"] },
  { name: "Sasha", link: ["https://centuriesofsound.com/"] },
  { name: "Sasha", link: ["https://www.converttobananas.com/"] },
  { name: "Colin", link: ["https://canitrundoom.org/"] },
  { name: "Matt", link: ["www.webcurios.co.uk"] },
  { name: "Andrei", link: ["https://revolutionarypapers.org/"] },
  { name: "Ricarda", link: ["https://www.fondazionefaustomelotti.org/catalogo-tipo/animals/"] },
  { name: "Noah / th3n04h", link: ["https://juniperlord.com/"] },
  { name: "gian", link: ["https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw?hl=en"] },
  { name: "Dan", link: ["nipplelinks.com"] },
  { name: "Steven", link: ["http://www.animalcrossingcommunity.com/"] },
  { name: "Katie", link: ["http://getwellsoon.labr.io/"] },
  { name: "latenac", link: ["https://cari.institute/aesthetics"] },
  { name: "Sam", link: ["https://somafm.com/"] },
  { name: "ToasterFaerie", link: ["https://pinboard.in/u:ToasterFaerie/t:wonderful_things/"] },
  { name: "Thomas", link: ["https://kristoffer.substack.com/"] },
  { name: "Colin", link: ["https://explore.marginalia.nu/"] },
  { name: "Shiney", link: ["https://greatergood.berkeley.edu/"] },
  { name: "cgreinhold", link: ["https://twomuch.rocks/"] },
  { name: "mugger", link: ["https://nalasinephro.bandcamp.com/album/space-18"] },
  { name: "Zac", link: ["https://en.wikipedia.org/wiki/List_of_unexplained_sounds"] },
  { name: "Joey", link: ["https://sprott.physics.wisc.edu/FRACTALS.HTM"] },
  { name: "John", link: ["https://zirk.us/@SmithsonianRoulette"] },
  { name: "Andrea", link: ["https://drought.climateservices.it/"] },
  { name: "Jo", link: ["http://tilde.club/~fishfinger/horrorscopes/"] },
  { name: "Polly", link: ["https://publicdomainreview.org/collection/the-corset-x-rays-of-dr-ludovic-o-followell-1908"] },
  { name: "Katrina", link: ["https://50watts.com/"] },
  { name: "Madeleine", link: ["siderealplexus.com"] },
  { name: "Dane", link: ["https://www.artstation.com/danehildreth"] },
  { name: "Gert", link: ["https://zoopzoopadventures.com"] },
  { name: "Finn", link: ["https://isi.org/intercollegiate-review/solzhenitsyn-explains-ldquobeauty-will-save-the-worldrdquo/"] },
  { name: "Cynthia", link: ["https://www.sendclown.com/"] },
  { name: "bre", link: ["https://www.yourworldoftext.com/"] },
  { name: "Youjung", link: ["https://utrecht.jp/"] },
  { name: "Lauren", link: ["Thewildopus.com"] },
  { name: "ghostmuji :3", link: ["https://ghostmuji.github.io/interactive/project-1/test.html"] },
  { name: "Spencer", link: ["https://we-b.site/"] },
  { name: "Greg Wolff", link: ["https://instagram.com/silknode"] },
  { name: "Toby", link: ["https://tvtropes.org/pmwiki/pmwiki.php/Main/CircusOfFear"] },
  { name: "Matthew", link: ["https://rotatingsandwiches.com/"] },
  { name: "Matharo", link: ["https://artvee.com/"] },
  { name: "Damjanski", link: ["https://rotatingsandwiches.com"] },
  { name: "Count", link: ["https://oaklandlibrary.org/found-in-a-library-book/"] },
  { name: "Toby", link: ["https://sit.sonnet.io/"] },
  { name: "Mufadal", link: ["https://www.lpoty.co.uk/gallery/2022/urban-life"] },
  { name: "Suraj", link: ["https://www.digitization.wiki/"] },
  { name: "Suraj", link: ["https://killsixbilliondemons.com/"] },
  { name: "Jason", link: ["https://imslp.org/"] },
  { name: "Donaldo", link: ["https://www.stitcher.com/show/missing-richard-simmons"] },
  { name: "Thea", link: ["https://asdfjklsemicolon.com/"] },
  { name: "Glenn", link: ["https://blueballfixed.ytmnd.com/"] },
  { name: "Ruth", link: ["https://dan-ball.jp/en/javagame/dust"] },
  { name: "Tori", link: ["https://taiwandatastories.com/bubble-tea-guide/?utm_campaign=mb&utm_medium=newsletter&utm_source=morning_brew"] },
];
